package com.gympro.app.auth.dto;

import com.gympro.app.base.type.base.BaseDTO;
import io.swagger.annotations.ApiModel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.annotation.Generated;

@Generated("Generated by model-gen framework")
@Setter
@Getter
@EqualsAndHashCode(callSuper = true)
@ToString
@ApiModel("Address")
public class AddressDTO extends BaseDTO {
    private String country;
    
    private String city;
    
    private long pinCode;
    
    private String county;
    
    private String addressLine1;
    
    private String addressLine2;
    
    private String state;
    
    private String isoCountry;
    
    private boolean primary;
    
}
