package com.gympro.app.auth.dto;

import com.gympro.app.base.type.base.BaseDTO;
import io.swagger.annotations.ApiModel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.annotation.Generated;

@Generated("Generated by model-gen framework")
@Setter
@Getter
@EqualsAndHashCode(callSuper = true)
@ToString
@ApiModel("FeatureAccess")
public class FeatureAccessDTO extends BaseDTO {
    private String featureId;
    
    private String method;
    
    private String featureName;
    
    private String featureUrl;
    
}
