package com.gympro.app.auth.dto;

import io.swagger.annotations.ApiModel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.gympro.app.base.type.base.BaseDTO;


import javax.annotation.Generated;

@Generated("Generated by model-gen framework")
@Setter
@Getter
@EqualsAndHashCode(callSuper = true)
@ToString
@ApiModel("Name")
public class NameDTO extends BaseDTO {
    private String lastName;
    
    private String firstName;
    
    private String middleName;
    
}
