package com.gympro.app.auth.dto;

import io.swagger.annotations.ApiModel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.Set;
import com.gympro.app.base.type.base.BaseDTO;


import javax.annotation.Generated;

@Generated("Generated by model-gen framework")
@Setter
@Getter
@EqualsAndHashCode(callSuper = true)
@ToString
@ApiModel("User")
public class UserDTO extends BaseDTO {
    private Set<FeatureAccessDTO> featureAccess;
    
    private Set<AddressDTO> addresses;
    
    private String password;
    
    private NameDTO name;
    
    private String employeeId;
    
    private String mailId;
    
    private String designation;
    
    private String status;
    
}
